### ISSUE TITLE
Cannot connect to DSE 4.6.2 with latest driver

### ISSUE THREAD

**Issue by 46labs** [datastax/ruby-driver#68]
Only affects latest 2.1.3 ruby-driver. Older versions connect fine. 

DSE 4.6.2 (Cassandra 2.0.12.274)

/usr/local/rvm/gems/ruby-2.2.1/gems/cassandra-driver-2.1.3/lib/cassandra/cluster/schema/type_parser.rb:134:in `lookup_type': nil is not a symbol nor a string (TypeError)
        from /usr/local/rvm/gems/ruby-2.2.1/gems/cassandra-driver-2.1.3/lib/cassandra/cluster/schema/type_parser.rb:103:in `create_type'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/cassandra-driver-2.1.3/lib/cassandra/cluster/schema/type_parser.rb:83:in `create_result'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/cassandra-driver-2.1.3/lib/cassandra/cluster/schema/type_parser.rb:53:in `parse'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/cassandra-driver-2.1.3/lib/cassandra/cluster/schema.rb:252:in `create_table'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/cassandra-driver-2.1.3/lib/cassandra/cluster/schema.rb:91:in `block in update_keyspace'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/cassandra-driver-2.1.3/lib/cassandra/cluster/schema.rb:89:in `each'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/cassandra-driver-2.1.3/lib/cassandra/cluster/schema.rb:89:in `each_with_object'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/cassandra-driver-2.1.3/lib/cassandra/cluster/schema.rb:89:in `update_keyspace'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/cassandra-driver-2.1.3/lib/cassandra/cluster/schema.rb:72:in `block in update_keyspaces'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/cassandra-driver-2.1.3/lib/cassandra/cluster/schema.rb:69:in `each'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/cassandra-driver-2.1.3/lib/cassandra/cluster/schema.rb:69:in `update_keyspaces'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/cassandra-driver-2.1.3/lib/cassandra/cluster/control_connection.rb:260:in `block in refresh_schema_async'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/ione-1.2.0/lib/ione/future.rb:348:in `call'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/ione-1.2.0/lib/ione/future.rb:348:in `block in map'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/ione-1.2.0/lib/ione/future.rb:704:in `call'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/ione-1.2.0/lib/ione/future.rb:704:in `call_listener'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/ione-1.2.0/lib/ione/future.rb:743:in `block in resolve'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/ione-1.2.0/lib/ione/future.rb:742:in `each'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/ione-1.2.0/lib/ione/future.rb:742:in `resolve'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/ione-1.2.0/lib/ione/future.rb:787:in `block (2 levels) in initialize'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/ione-1.2.0/lib/ione/future.rb:704:in `call'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/ione-1.2.0/lib/ione/future.rb:704:in `call_listener'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/ione-1.2.0/lib/ione/future.rb:743:in `block in resolve'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/ione-1.2.0/lib/ione/future.rb:742:in `each'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/ione-1.2.0/lib/ione/future.rb:742:in `resolve'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/ione-1.2.0/lib/ione/future.rb:348:in `block in map'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/ione-1.2.0/lib/ione/future.rb:704:in `call'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/ione-1.2.0/lib/ione/future.rb:704:in `call_listener'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/ione-1.2.0/lib/ione/future.rb:743:in `block in resolve'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/ione-1.2.0/lib/ione/future.rb:742:in `each'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/ione-1.2.0/lib/ione/future.rb:742:in `resolve'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/ione-1.2.0/lib/ione/future.rb:29:in `fulfill'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/cassandra-driver-2.1.3/lib/cassandra/protocol/cql_protocol_handler.rb:241:in `complete_request'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/cassandra-driver-2.1.3/lib/cassandra/protocol/v1.rb:155:in `actual_decode'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/cassandra-driver-2.1.3/lib/cassandra/protocol/v1.rb:86:in `decode_header'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/cassandra-driver-2.1.3/lib/cassandra/protocol/v1.rb:64:in `<<'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/cassandra-driver-2.1.3/lib/cassandra/protocol/cql_protocol_handler.rb:271:in `receive_data'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/ione-1.2.0/lib/ione/io/base_connection.rb:162:in `call'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/ione-1.2.0/lib/ione/io/base_connection.rb:162:in `read'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/ione-1.2.0/lib/ione/io/io_reactor.rb:396:in `block in tick'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/ione-1.2.0/lib/ione/io/io_reactor.rb:396:in `each'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/ione-1.2.0/lib/ione/io/io_reactor.rb:396:in `tick'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/ione-1.2.0/lib/ione/io/io_reactor.rb:133:in `block in start'

**Comment by avalanche123** [comment]
discussion moved to jira
