### ISSUE TITLE
Documentation on Downgrading Consistency

### ISSUE THREAD

**Issue by Davidslv** [datastax/ruby-driver#70]
Hi guys,

I found this page [Downgrading Consistency](http://datastax.github.io/ruby-driver/features/retry_policies/downgrading_consistency/) - which was what I was looking for, but it's not mentioned on the [Retry Policies](http://datastax.github.io/ruby-driver/features/retry_policies/) where I was hopping to find it, and I can't seem to find a link to it either, I'm not sure if it was forgotten at some point or I didn't see it somewhere else.

Thank you

**Comment by avalanche123** [comment]
It is mentioned under the "read more" section
